version: '3.8'

services:
  db_users:
    container_name: db_users
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_users
    image: postgres:14.3-alpine
